### ISSUE TITLE
Addon preventing logging out in any form while active.

### ISSUE THREAD

**Issue by lownignitus** [perrottg/WorldBossStatus#12]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'WorldBossStatus' tried to call the protected function 'oldQuit()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `oldQuit'
WorldBossStatus\WorldBossStatus-5.6.lua:1632: in function `Quit'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
nil

**Comment by perrottg** [comment]
This has been resolved in v5.7.
