### ISSUE TITLE
Patch 8.0.1 : LUA ERROR

### ISSUE THREAD

**Issue by Galiwyx** [perrottg/WorldBossStatus#15]
Message: Interface\AddOns\WorldBossStatus\WorldBossStatus.lua:658: attempt to index global 'C_MapCanvas' (a nil value)
Time: Wed Jul 18 11:21:23 2018
Count: 1
Stack: Interface\AddOns\WorldBossStatus\WorldBossStatus.lua:658: attempt to index global 'C_MapCanvas' (a nil value)
[C]: ?
Interface\AddOns\WorldBossStatus\WorldBossStatus.lua:658: in function `GetActiveWorldBosses'
Interface\AddOns\WorldBossStatus\WorldBossStatus.lua:1635: in function `func'
...AddOns\ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:57: in function <...AddOns\ElvUI\Libraries\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:

**Comment by perrottg** [comment]
This has been resolved in v5.9,
